//
//  Photo+CoreDataProperties.swift
//  WorkHaven
//
//  Created by WorkHaven Team on 2024
//  Copyright © 2024 WorkHaven. All rights reserved.
//

import Foundation
import CoreData

/**
 * Photo+CoreDataProperties provides the Core Data property definitions
 * for the Photo entity. This file is automatically generated and should
 * not be manually modified.
 */
extension Photo {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<Photo> {
        return NSFetchRequest<Photo>(entityName: "Photo")
    }

    /// Binary data containing the image (JPEG format) - deprecated in favor of CloudKit assets
    @NSManaged public var imageData: Data?
    
    /// CloudKit asset identifier for photo synchronization across devices
    @NSManaged public var photoAsset: String?
    
    /// Timestamp when the photo was taken or added
    @NSManaged public var timestamp: Date
    
    /// CloudKit record identifier for synchronization
    @NSManaged public var cloudKitRecordID: String
    
    /// The spot this photo belongs to (many-to-one relationship)
    @NSManaged public var spot: Spot?

}

extension Photo : Identifiable {

}
