//
//  UserTip+CoreDataProperties.swift
//  WorkHaven
//
//  Created by WorkHaven Team on 2024
//  Copyright © 2024 WorkHaven. All rights reserved.
//

import Foundation
import CoreData

/**
 * UserTip+CoreDataProperties provides the Core Data property definitions
 * for the UserTip entity. This file is automatically generated and should
 * not be manually modified.
 */
extension UserTip {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<UserTip> {
        return NSFetchRequest<UserTip>(entityName: "UserTip")
    }

    /// The text content of the user tip
    @NSManaged public var text: String
    
    /// Number of likes for this tip
    @NSManaged public var likes: Int16
    
    /// Number of dislikes for this tip
    @NSManaged public var dislikes: Int16
    
    /// Timestamp when the tip was created
    @NSManaged public var timestamp: Date
    
    /// CloudKit record identifier for synchronization
    @NSManaged public var cloudKitRecordID: String
    
    /// Supabase `spot_tips.id` when synced from community backend
    @NSManaged public var supabaseId: String?
    
    /// The spot this tip belongs to (many-to-one relationship)
    @NSManaged public var spot: Spot?

}

extension UserTip : Identifiable {

}
