//
//  UserRating+CoreDataProperties.swift
//  WorkHaven
//
//  Created by WorkHaven Team on 2024
//  Copyright © 2024 WorkHaven. All rights reserved.
//

import Foundation
import CoreData

/**
 * UserRating+CoreDataProperties provides the Core Data property definitions
 * for the UserRating entity. This file is automatically generated and should
 * not be manually modified.
 */
extension UserRating {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<UserRating> {
        return NSFetchRequest<UserRating>(entityName: "UserRating")
    }

    /// WiFi quality rating on a scale of 1-5
    @NSManaged public var wifi: Int16
    
    /// Noise level description (e.g., "Quiet", "Loud", "Moderate")
    @NSManaged public var noise: String
    
    /// Whether electrical outlets/plugs are available
    @NSManaged public var plugs: Bool
    
    /// User's tips and additional notes about the spot
    @NSManaged public var tip: String
    
    /// Many-to-one relationship to the associated Spot
    @NSManaged public var spot: Spot?

}

extension UserRating : Identifiable {

}
