//
//  UserFavorite+CoreDataProperties.swift
//  WorkHaven
//
//  Created by WorkHaven Team on 2024
//  Copyright © 2024 WorkHaven. All rights reserved.
//

import Foundation
import CoreData

/**
 * UserFavorite+CoreDataProperties provides the Core Data property definitions
 * for the UserFavorite entity. This file is automatically generated and should
 * not be manually modified.
 */
extension UserFavorite {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<UserFavorite> {
        return NSFetchRequest<UserFavorite>(entityName: "UserFavorite")
    }

    /// Timestamp when the spot was favorited by the user
    @NSManaged public var timestamp: Date
    
    /// CloudKit record identifier for synchronization
    @NSManaged public var cloudKitRecordID: String
    
    /// The spot that this favorite refers to
    @NSManaged public var spot: Spot?

}

extension UserFavorite : Identifiable {

}
